# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6888429ce025c5e4f3607943dc534731a1a1ba066f93b79c95d0f8db2557137da8c03155c85cd5abce1278382b3871e1fbd34215868de08f8e2df4d52ecf4f1

test:
  secret_key_base: 59edd1b06e2be98103b8666cdf8e73923a4ce412c889e26073508a2b232fdbb333adaab659329ac3e926f488f6b85753e0186094dcfac6ccc12cae579595df05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
